name: Format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # "git restore ." discards changes to package-lock.json
      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile --ignore-scripts
          git restore .

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Format'
